steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/governance:$COMMIT_SHA'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/governance:$COMMIT_SHA'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'governance'
      - '--image=europe-west2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/governance:$COMMIT_SHA'
      - '--region=europe-west2'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--set-env-vars=NODE_ENV=production'

images:
  - 'europe-west2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/governance:$COMMIT_SHA'
